import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { BlockchainContextProvider } from "./providers/blockchain.provider";
import NavBar from "./navbar";
import "./globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BlockchainContextProvider>
          <NavBar />
          {children}
          </BlockchainContextProvider>
      </body>
    </html>
  );
}
